alias xcode-nuke-dd='rm -rf ~/Library/Developer/Xcode/DerivedData/*'
alias xcode-nuke-archives='rm -rf ~/Library/Developer/Xcode/Archives/*'
alias xcode-activate-main='sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer'
alias xcode-activate-beta='sudo xcode-select --switch /Applications/Xcode-beta.app/Contents/Developer'
alias dis='objdump -disassemble -x86-asm-syntax=intel -macho -no-show-raw-insn -g -source'
